POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Another Summit",
  "details": "Evento de programação",
  "maximumAttendees": 10
}

###

POST http://localhost:3333/events/95564656-4ee8-4b0d-b02c-0b08284c1cb6/attendees
Content-Type: application/json

{
  "name": "John Doo",
  "email": "john@email.com"
}

###
GET http://localhost:3333/events/bfa619f2-e367-4190-8e12-e19b19a5ab0c

###
GET http://localhost:3333/attendees/9eqmSf_9eqmSf_NkbNkb/badge

###
GET http://localhost:3333/attendees/9eqmSf_Nkb/check-in

###
GET http://localhost:3333/events/bfa619f2-e367-4190-8e12-e19b19a5ab0c/attendees?query=&pageIndex=