POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Another Summit",
  "details": "Evento de programação",
  "maximumAttendees": 5
}

###
POST http://localhost:3333/events/95564656-4ee8-4b0d-b02c-0b08284c1cb6/attendees
Content-Type: application/json

{
  "name": "Evandro Costa",
  "email": "evandro@email.com"
}

###
GET http://localhost:3333/events/95564656-4ee8-4b0d-b02c-0b08284c1cb6

###
GET http://localhost:3333/attendees/5zQzzdDN4j/badge

###
GET http://localhost:3333/attendees/5zQzzdDN4j/check-in

###
GET http://localhost:3333/events/95564656-4ee8-4b0d-b02c-0b08284c1cb6/attendees?query=evandro